apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: elasticsearch
  template:
    metadata:
      labels:
        run: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
          imagePullPolicy: Always
          env:
            - name: discovery.type
              value: single-node
            - name: cluster.name
              value: elasticsearch
          ports:
            - containerPort: 9300
              name: nodes
            - containerPort: 9200
              name: client
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  type: NodePort
  selector:
    run: elasticsearch
  ports:
    - port: 9200
      name: client
      targetPort: 9200
    - port: 9300
      name: nodes
      targetPort: 9300
